const rootDir = process.cwd();

const COLUMNS_ANALYSIS = [
  "active",
  "version",
  "id_hsb", 
  "code",
  "code_sil",
  "code_aes", 
  "code_cns",
  "label",
  "label_en",
  "label_de",
  "synonymous",
  "synonymous_en",
  "synonymous_de",
  "subcontracted",
  "laboratory",
  "urgent",
  "diet",
  "comment_diet",
  "comment_diet_en",
  "comment_diet_de",
  "forbidden_at_home",
  "empty_stomach",
  "consent_required",
  "stability_before_preprocessing",
  "time_limit_add_analysis",  
  "comment_sample",
  "comment_sample_en",
  "comment_sample_de",
  "comment_preprocessing",
  "comment_preprocessing_en",
  "comment_preprocessing_de",  
  "centrifugation",
  "analyser",
  "volume_pipette",
  "time_limit_for_results",
  "monday",
  "tuesday",
  "wednesday",
  "thursday",
  "friday",
  "saturday",
  "sunday",
  "tubes",
  "permissions",
  "documents"
];

const COLUMNS_TUBES = [
  "active",
  "version",
  "code",
  "code_sil",
  "label",
  "public_description",
  "public_description_en",
  "public_description_de",
  "id_img",
  "display_order",
  "timer",
  "timer_before_result",
  "regex",
  "protected_from_light",
  "aliquot"
];

const HEADINGS_ANALYSIS = [[
  "ACTIVE",
  "Version",
  "ID HSB",
  "Code analyse",
  "Code SIL",
  "Codes AES",
  "Codes tarifs",
  "Libellé de l'analyse",
  "Libellé EN",
  "Libellé DE",
  "Synonymes",
  "Synonymes EN",
  "Synonymes DE",
  "Sous-traité",
  "Sous-traitant",
  "Urgent",
  "Régime alimentaire",
  "Commentaire régime",
  "Commentaire régime EN",
  "Commentaire régime DE",
  "Interdit à domicile",
  "À jeun",
  "Formulaire de consentement requis",
  "Stabilité avant pré-traitement (heure, à TA)",
  "Délai rajout analyse (en heure)",
  "Note pour prélèvement",
  "Note pour prélèvement EN",
  "Note pour prélèvement DE",
  "Note avant pré-traitement",
  "Note avant pré-traitement EN",
  "Note avant pré-traitement DE",
  "Programme centrifugation",
  "Analyseur",
  "Volume pipetage (en μL)",
  "Délai de rendu (en heures)",
  "Lundi",
  "Mardi",
  "Mercredi",	
  "Jeudi",
  "Vendredi",	
  "Samedi",
  "Dimanche",
  "Tubes",
  "Permissions",
  "Documents"
]];

const HEADINGS_TUBES = [[
  "ACTIF",
  "Version",	
  "Code tube",	
  "Code SIL",
  "Libellé du tube",
  "Description externe",
  "Description EN",
  "Description DE",
  "Pictogramme",
  "Ordre affichage",
  "Timer",
  "Temps avant résultat",
  "Règle de validation du code barres",
  "Abri de la lumière",
  "Aliquot"
]];

const PATHS = {
  UPLOAD_REP: rootDir + "/public/uploads"
};

const TYPE_IMPORT = "BNXT";

module.exports = { 
  HEADINGS_ANALYSIS,
  HEADINGS_TUBES,
  COLUMNS_ANALYSIS,
  COLUMNS_TUBES,
  PATHS,
  TYPE_IMPORT
};